package com.netflix.sunjeetsonboardingroot.startup;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Namespaces {

    public static final Map<String, Long> NAMESPACE_VERSIONS = new HashMap<String, Long>() {{
        put("vms-feather", 20200302185411631l);
        put("vmsconverter-muon", 20200304220218561l);
        put("astrid.v1", 20200304214554088l);
        put("gatekeeper2_status_prod", 20200304215735102l);

    }};

    public static final List<String> FEW_NAMESPACES = Arrays.asList("vms.popularViewables.topN", "cuptokenrecords.v3"); // "vms-feather"

    public static final List<String> NAMESPACES = Arrays.asList(
            "snoke-mapper-stage",
            "hexter.ContentSamplingCollections",
            "ocp.routes.prefixes.warned.rpki",
            "packageDealCountry-feed",
            "promo.asset.requirement.v3",
            "cinder.gatekeeper.whiplash.subdub",
            "cuptokenrecords.v3",
            "gk_overrides",
            "oscar.memento.localizedTitle",
            "CsnaPredictions.v1",
            "promo.asset.validator.v2.whim",
            "algo.vms.v1.all.final",
            "astrid.v1",
            "dei-asset.right-1.2",
            "exhibit.launchdates.1.0",
            "entity_annotations_v2",
            "BestCbPredictions.v1",
            "ocp.routes.prefixes.filtered.rpki",
            "cinder.oscar.memento.videoType",
            "streaming.highriskcache.v1",
            "dei-exclusive.window-1.0",
            "entity_annotations_v3",
            "ocp-ftf-pipeline",
            "open-connect-partner-comms-templates",
            "movietitle.localizedtitle",
            "PopularEpisodes_v0",
            "packageEntityDealWithOverrideCountriesFeed-feed",
            "cinder.oscar.memento.rollout",
            "cinder.oscar.dei.memento.videoGeneral",
            "sdapi.editorialpromotion-v4",
            "cinder.oscar.memento.searchableTitles",
            "ocp.routes.prefixes.warned",
            "sdapi.editorialpromotion-v2",
            "allocation.metadata.v4.dev",
            "ocp.rankedstacks.v4",
            "sdapi.editorialpromotion-v1",
            "PopularEpisodes.v2",
            "cpe.metrix.athenaData.v2",
            "gatekeeper2_status_oracle",
            "tick.tock.guice.v3",
            "chewbacca-directory-staging",
            "externalpartnerfeed_prod",
            "promo.asset.validator.v2.promoranker",
            "sims-cslim",
            "cinder.gatekeeper.whiplash.fdd",
            "ocp-throttling-v1-canary",
            "cpe.metrix.crystalBallData.v2",
            "allocation.metadata.v3.dev",
            "mulan_movieratings_alpha",
            "contentpreview-prod",
            "contentpreview-staging",
            "algo.vms.v1.micro.final",
            "vms-feather_override",
            "ocp.routes.rpki.roa",
            "pvr-tags-unstratified-365",
            "titlecutter_prod",
            "HalPredictions.v1",
            "ocp-throttling-v1-jschek",
            "tick.tock.titusguice.v3",
            "movietitle_prod",
            "pvr-titlegranular-data",
            "ocp.routes.missing",
            "exhibit_incremental",
            "vms-vmsdev_pbm",
            "streaming.ocschema.v2",
            "streaming.ocschema.v1",
            "cinder.oscar.memento.videoColors",
            "ocp.routes.rankedstacks.filtered",
            "cinder.arcus.movieRequirements",
            "cinder.gatekeeper.whiplash.status",
            "movie-country-language-earliestdate-namespace",
            "cinder.award.videoAward",
            "allocation.metadata.v1.dev",
            "fdd",
            "dray",
            "ocp-throttling-v1",
            "entity_metadata_tags_v1",
            "ocp-ftf-pipeline-canary",
            "mpbl_v5",
            "mce_viewables",
            "dei-window-1.0",
            "streaming.geoproxy.config.proxy.v2",
            "vms.popularViewables.topN",
            "PredictedVerticals.v1",
            "tick.tock.spring.v3",
            "language-merch",
            "characterservice_alpha",
            "cinder.oscar.memento.personVideo",
            "dradis-model-v1",
            "gatekeeper2_status_prod",
            "ocp.routes.v3",
            "upm-test3-cybertron-data",
            "mcerequiredstreamcounts",
            "ocp-ftf-pipeline-jschek",
            "NosCbPredictions.v1",
            "cinder.oscar.memento.similarTitles",
            "exhibit.deal.attribute.v1",
            "ocp-deployment-groups-v1-jschek",
            "movietitle_preprod",
            "dei-attribute-1.0",
            "PersonnelPredictions.v1",
            "promotion-blacklist-v2",
            "octransformer_prod",
            "ocp.routes.prefixes.warned.all",
            "streaming.octopgear.cinder.v1",
            "promo.asset.validator.update-recipes.v2.billboard",
            "chewbacca-users-latest-staging",
            "snoke-mapper-prod",
            "streaming.octopgear.stage.v2",
            "hexter.ContentSamplingCustom",
            "persons_prod",
            "chewbacca-directory",
            "upm-cybertron-data",
            "cpe-timetable-v3",
            "ocdownloadables",
            "cinder.oscar.memento.localizedMetaData",
            "oscar_entityfeed_alpha",
            "cinder.oscar.memento.videoDate",
            "search.async.dataloader.cinder.promotionAndBoosting",
            "dse.cuesheet.v3",
            "dynamiccopy_v2",
            "ocp.routes.prefixes.rejected",
            "dse.cuesheet.v4",
            "astroboy_alpha",
            "cpe.metrix.halData.v2",
            "CbPredictions.v5",
            "CompsCbPredictions.v2",
            "allin-config-data",
            "CompsCbPredictions.v5",
            "cinder.oscar.memento.videoGeneral",
            "ocp-deployment-intents",
            "promo.asset.validator.v2.billboard",
            "CbPredictions.v2",
            "CbPredictions.v4",
            "packagedealcountry_incremental",
            "JediContent_jedistaging_v1",
            "ocp.routes.prefixes.filtered",
            "mcevmsfeeds.image.v3",
            "promo.asset.validator.v2.ripple",
            "vms-vmsdev_jleibundguth_full",
            "gatekeeper2_status_preprod",
            "packageDealCountry-ampmigration",
            "titlesensitivity",
            "pvr.unpersonalized.v1",
            "CbHistory.v1",
            "asset-validator-v1",
            "ocp-deployment-groups-v1",
            "cinder.oscar.memento.entityGroups",
            "ImagePipeTest.arofer.v3",
            "vms-feather",
            "cinder.mulan.whiplash.maturityRatings",
            "streaming.vayurules.v1",
            "promo.asset.validator.v2.messaging",
            "ocp-ftf-pipeline-baseline",
            "vmsconverter-muon",
            "ocp-dlToPackageMapping",
            "megaphone-alpha",
            "turboCollection_localization_v2",
            "JediContent_jedidocs_v1",
            "cinder.oscar.memento.showCountryLabel",
            "hexter.ContentSamplingAvail",
            "timecode_annotations_v1",
            "cinder.oscar.memento.showSeasonEpisode",
            "shiro_alpha",
            "dei-rights-attribute-1.0",
            "search.async.dataloader.cinder.queryprocessing",
            "shiro-cinder-alpha",
            "sdp_sweep",
            "promo.asset.validator.v2.vxs",
            "cinder.oscar.memento.supplemental",
            "chewbacca-users-latest-prod",
            "upm-test4-cybertron-data",
            "titlesensitivity_vmsdev_dsu",
            "finance.cuesheet.v1",
            "flexds_alpha",
            "cinder.oscar.memento.containers"

    );
}
